### ISSUE TITLE
Copy change for box next to video on main page.

### ISSUE THREAD

**Issue by Steve-Cook** [capital-chaplains/capchaps.org#3]
Please delete all of the text in the box to the right of the video on the main page except for the headline  "Life is tough...then we go to work. " and then delete all text in the box except the last sentence starting "Watch this video..."  The goal of all that text in between is to get the viewer to click on the video.  Less is more in this case.

**Comment by matt-cook** [comment]
Sounds good! I'll get this in this month.

**Comment by CorpChapsCom** [comment]
Matt - this issue ended up in CorpChaps.Com but should apply only to CapChaps.Org.

**Comment by matt-cook** [comment]
Done: http://capchaps.org/ c05ff1a1cf52ab93bfe311e4ef6d0c2f3a9de47a
