### ISSUE TITLE
Add WPR interview link to CapChaps.Org main page

### ISSUE THREAD

**Issue by Steve-Cook** [capital-chaplains/capchaps.org#6]
http://www.wpr.org/rise-chaplaincy-programs-workplace

Please add the following copy inside the grey box in the upper right-hand corner of the main page under the "Watch this video . . . " copy

"Listen to this objective Wisconsin Public Radio interview about workplace chaplaincy."  (Please link to the audio interview with the file on our own server please rather than WPR's webserver."

Many thanks!

**Comment by matt-cook** [comment]
I've linked it directly to WPR for now (always best to link directly to the source instead of mirroring, when possible). I've also downloaded the .mp3 so we have a backup copy if they remove the page.

Closed by: cf7a9fa99473ca6cb7f9bcc594624190bf4e4b13
